name: Deploy matrix2 Services

on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read JSON and set matrix
        id: set-matrix
        run: |
          cd configs
          matrix=$(jq -c '[ to_entries[] | { service: .key, rep: .value.rep, artifact: .value.artifact, jarname: .value.jarname } ]' manifest1.json)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  deploy:
    needs: generate-matrix
    runs-on: ubuntu-latest
    steps:
      -name: run echo "${{ fromJSON(needs.generate-matrix.outputs.matrix }}"
